Overload addMetaproperty
Bynder/bynder-java-sdk pull request #61
Opened 2021-07-07 16:51 UTC by erikd-spotify

Overload addMetaproperty to allow for multiple options via options array

2021-08-25 11:25 UTC, betacar requested changes
Hey @erikd-spotify! Thanks for this, could you please add some tests?

2021-08-30 09:28 UTC, betacar approved these changes
🐑 🇮🇹

2021-08-30 09:29 UTC, Arpit-Sharma-USC approved these changes

2021-08-30 11:20 UTC, merged

2021-08-30 12:13 UTC, betacar commented
@erikd-spotify Thank you for your contribution. This was included on the [2.2.11](https://github.com/Bynder/bynder-java-sdk/releases/tag/2.2.11) release.